project_id = "hguacltdrmckpcvycxzx"

[functions.razorpay-webhook]
verify_jwt = false

[functions.slot-signup-submit]
verify_jwt = false

[functions.slot-signup-file-url]
verify_jwt = false

[functions.email-dispatcher]
verify_jwt = false