// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hguacltdrmckpcvycxzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhndWFjbHRkcm1ja3BjdnljeHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTQ0NTYsImV4cCI6MjA2ODQzMDQ1Nn0.42bTu1A6xftm1BSK5d8kBc56-NryxrXdxmTKNoRwSJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});